version: '3'

networks:
  default:
    name: selfhosted

services:

  watchtower:
    image: containrrr/watchtower
    restart: unless-stopped
    security_opt:
      - seccomp:unconfined
      - apparmor:unconfined
    volumes:
      - /run/docker.sock:/var/run/docker.sock

  php:
    image: aeon/php
    build: ./apps/php/build
    restart: unless-stopped
    security_opt:
      - seccomp:unconfined
      - apparmor:unconfined
    volumes:
      - ./apps/php/rootfs/etc/php:/usr/local/etc/php:ro
      - ./apps/php/rootfs/etc/php-fpm.d:/usr/local/etc/php-fpm.d:ro
      - ./apps/php/rootfs/etc/php-fpm.conf:/usr/local/etc/php-fpm.conf:ro
      # Web
      - /srv/docker/nginx:/data
      # Public directories
      - /home/aeon/Public:/data/pw.vmm.public/aeon:ro
      - /home/cho/Public:/data/pw.vmm.public/cho:ro
      # Nextcloud
      - /home/aeon/Downloads:/data/pw.vmm.drive/data/aeon/files/Downloads
      - /home/aeon/Media:/data/pw.vmm.drive/data/aeon/files/Media
      - /home/aeon/Pictures:/data/pw.vmm.drive/data/aeon/files/Pictures
      - /home/aeon/Public:/data/pw.vmm.drive/data/aeon/files/Public

  nginx:
    image: aeon/nginx
    build: ./apps/nginx/build
    restart: unless-stopped
    security_opt:
      - seccomp:unconfined
      - apparmor:unconfined
    depends_on:
      - php
      - nginx-sso
      - netdata
      - code
      - photoprism
      - jellyfin
      - flood
      - neko
    healthcheck:
      test: [ 'CMD', 'curl', '-i', 'http://localhost' ]
      interval: 60s
      timeout: 10s
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./apps/nginx/rootfs/etc/nginx:/etc/nginx:ro
      - /etc/letsencrypt/live:/etc/letsencrypt/live:ro
      - /etc/letsencrypt/archive:/etc/letsencrypt/archive:ro
      # Web
      - /srv/docker/nginx:/data
      # Public directories
      - /home/aeon/Public:/data/pw.vmm.public/aeon:ro
      - /home/cho/Public:/data/pw.vmm.public/cho:ro
      # Nextcloud
      - /home/aeon/Downloads:/data/pw.vmm.drive/data/aeon/files/Downloads
      - /home/aeon/Media:/data/pw.vmm.drive/data/aeon/files/Media
      - /home/aeon/Pictures:/data/pw.vmm.drive/data/aeon/files/Pictures
      - /home/aeon/Public:/data/pw.vmm.drive/data/aeon/files/Public

  nginx-sso:
    image: luzifer/nginx-sso:latest
    restart: unless-stopped
    security_opt:
      - seccomp:unconfined
      - apparmor:unconfined
    volumes:
      - ./apps/nginx-sso/rootfs/data/config.yaml:/data/config.yaml:ro

  mariadb:
    image: mariadb:latest
    command: mysqld --transaction-isolation=READ-COMMITTED
      --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
      --max-connections=512 --innodb-rollback-on-timeout=OFF
      --innodb-lock-wait-timeout=50 --skip-innodb-read-only-compressed
    restart: unless-stopped
    security_opt:
      - seccomp:unconfined
      - apparmor:unconfined
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "--silent" ]
      interval: 60s
      timeout: 10s
    env_file:
      - ./apps/mariadb/secure.env
    volumes:
      - /srv/docker/mariadb:/var/lib/mysql

  sonic:
    image: valeriansaliou/sonic:v1.3.0
    restart: unless-stopped
    security_opt:
      - seccomp:unconfined
      - apparmor:unconfined
    env_file:
      - ./apps/sonic/secure.env
    volumes:
      - ./apps/sonic/rootfs/etc/sonic.cfg:/etc/sonic.cfg:ro
      - /srv/docker/sonic:/var/lib/sonic

  netdata:
    image: netdata/netdata:latest
    restart: unless-stopped
    cap_add:
      - SYS_PTRACE
    security_opt:
      - seccomp:unconfined
      - apparmor:unconfined
    environment:
      NVIDIA_DRIVER_CAPABILITIES: all
      NVIDIA_VISIBLE_DEVICES: all
    volumes:
      - ./apps/netdata/rootfs/etc/netdata:/etc/netdata:ro
      - /srv/docker/netdata/lib:/var/lib/netdata
      - /srv/docker/netdata/cache:/var/cache/netdata
      - /etc/passwd:/host/etc/passwd:ro
      - /etc/group:/host/etc/group:ro
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /etc/os-release:/host/etc/os-release:ro
    deploy:
      resources:
        reservations:
          devices:
            - capabilities: [ gpu ]

  code:
    user: 1000:1000
    build: ./apps/code/build
    image: aeon/code
    restart: unless-stopped
    security_opt:
      - seccomp:unconfined
      - apparmor:unconfined
    volumes:
      - ./apps/code/rootfs/home/code/.config/code-server:/home/code/.config/code-server:ro
      - ~/.config/Code - Insiders:/home/code/.local/share/code-server
      - ~/.dotfiles:/home/code/.dotfiles

  photoprism:
    user: 1000:1000
    image: photoprism/photoprism:preview
    restart: unless-stopped
    security_opt:
      - seccomp:unconfined
      - apparmor:unconfined
    depends_on:
      - mariadb
    healthcheck:
      test: [ 'CMD', 'photoprism', 'status' ]
      interval: 60s
      timeout: 10s
    env_file:
      - ./apps/photoprism/config.env
      - ./apps/photoprism/secure.env
    environment:
      NVIDIA_DRIVER_CAPABILITIES: all
      NVIDIA_VISIBLE_DEVICES: all
    working_dir: /photoprism
    volumes:
      - ~/Pictures:/photoprism/originals
      - /srv/docker/photoprism/storage:/photoprism/storage
    deploy:
      resources:
        reservations:
          devices:
            - capabilities: [ gpu ]

  jellyfin:
    user: 1000:1000
    image: jellyfin/jellyfin
    restart: unless-stopped
    security_opt:
      - seccomp:unconfined
      - apparmor:unconfined
    volumes:
      - /srv/docker/jellyfin/config:/config
      - /srv/docker/jellyfin/cache:/cache
      - /srv/docker/jellyfin/media:/media
    environment:
      NVIDIA_DRIVER_CAPABILITIES: all
      NVIDIA_VISIBLE_DEVICES: all
    deploy:
      resources:
        reservations:
          devices:
            - capabilities: [ gpu ]

  rtorrent:
    image: looselyrigorous/rtorrent:latest
    restart: unless-stopped
    security_opt:
      - seccomp:unconfined
      - apparmor:unconfined
    environment:
      - PUID=1000
      - PGID=1000
    volumes:
      - ./apps/rtorrent/rootfs/config:/config
      - ~/Downloads:/watch
      - ~/Downloads:/download

  flood:
    image: aeon/flood
    build: ./apps/flood/build
    command: flood --host 0.0.0.0 --port 8000 --rundir /data --auth none --rthost
      rtorrent --rtport 5050
    restart: unless-stopped
    security_opt:
      - seccomp:unconfined
      - apparmor:unconfined
    depends_on:
      - rtorrent
    volumes:
      - /srv/docker/flood:/data
      - ~/Downloads:/download

  neko:
    image: aeon/neko:chromium
    restart: unless-stopped
    security_opt:
      - seccomp:unconfined
      - apparmor:unconfined
    cap_add:
      - SYS_ADMIN
    shm_size: 2gb
    ports:
      - 52000-52100:52000-52100/udp
    env_file:
      - ./apps/neko/config.env
      - ./apps/neko/secure.env
    volumes:
      - ./apps/neko/rootfs/etc/chromium/policies/managed/policies.json:/etc/chromium/policies/managed/policies.json:ro
      - ./apps/neko/rootfs/home/neko/.config/chromium/Default/Preferences:/home/neko/.config/chromium/Default/Preferences:ro
  # archivebox:
  #   image: archivebox/archivebox:master
  #   command: server --quick-init 0.0.0.0:8000
  #   restart: unless-stopped
  #   security_opt:
  #     - seccomp:unconfined
  #     - apparmor:unconfined
  #   depends_on:
  #     - sonic
  #   env_file:
  #     - ./apps/archivebox/config.env
  #     - ./apps/archivebox/secure.env
  #   volumes:
  #     - /srv/docker/archivebox:/data
